import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./convesProvider";
import { BseTradesProvider } from "@/context/BseTradesContext";
import { NseTradesProvider } from "@/context/NseTradeContext";
import { UserProvider } from "@/context/UserContext";
import Chatbot from "@/components/chatBot/ChatBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClientProvider>
        <BseTradesProvider>
          <NseTradesProvider>
            <UserProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <Chatbot/>
                {children}
              </body>
            </UserProvider>
          </NseTradesProvider>
        </BseTradesProvider>
      </ConvexClientProvider>
    </html>
  );
}
